work around key resolution error
brick_config.config.ConfigResolutionError: unable to evaluate $Bricks.Phrase.PhraseTable.reordering in the configuration Experiment.parts.PhraseTable0.reordering

TODO: The ordering bug of inheritance is still there. cannot extend a key which itself is inherited, because inheritance tree is not traversed properly?!